name: "Daily Integration"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          git clone https://gitdab.com/cadence/Carbon .
      - name: "Install Node toolchain"
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: "Build Carbon package"
        env:
          NODE_ENV: production
        run: |
          npm install -D
          npm run build
          mv build carbon
          tar -zcvf carbon.tar.gz carbon
      - name: "Upload Carbon package"
        uses: actions/upload-artifact@v2
        with:
          name: carbon
          path: carbon.tar.gz

  package:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: "Unpack Carbon package"
        uses: actions/download-artifact@v2
        with:
          name: carbon

      - name: "Prepare Carbon for deployment"
        shell: bash
        run: |
          tar -zxvf carbon.tar.gz -C /tmp
          mkdir thecore
          xargs -n1 cp -pr /tmp/carbon <<< "thecore/carbon.thecore.city"
      - name: "Upload Carbon package for The Core"
        uses: actions/upload-artifact@v2
        with:
          name: carbon-thecore
          path: thecore

  deploy:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: "Unpack Carbon package for The Core"
        uses: actions/download-artifact@v2
        with:
          name: carbon-thecore

      - name: "Deploy Carbon to The Core"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CI_DEPLOYER_SSH_ADDRESS_THECORE }}
          username: ${{ secrets.CI_DEPLOYER_SSH_USER }}
          key: ${{ secrets.CI_DEPLOYER_SSH_KEY_THECORE }}
          port: ${{ secrets.CI_DEPLOYER_SSH_PORT }}
          source: carbon.thecore.city
          target: /srv/http/carbon.thecore.city
          strip_components: 1
          rm: true
